In [1]:
#install python package - Numpy

In [2]:
#install python package - Numpy
#pip install numpy

In [3]:
import numpy as np

In [4]:
myList=[1,2,3,4,5]

In [5]:
print(myList)

[1, 2, 3, 4, 5]


In [6]:
type(myList)

list

In [7]:
#dir(np)

In [8]:
#help(np)

In [9]:
arr=np.array(myList)

In [10]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
#shape of the array
arr.shape

(5,)

In [12]:
arr.size

5

In [13]:
my_List1=[1,2,3,4,5]
my_List2=[3,5,7,8,5]
my_List3=[5,7,2,5,9]

arr=np.array([my_List1,my_List2,my_List3])

In [89]:
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
arr.shape

(3, 5)

In [16]:
arr

array([[1, 2, 3, 4, 5],
       [3, 5, 7, 8, 5],
       [5, 7, 2, 5, 9]])

In [17]:
arr.size

15

In [18]:
#Numpy array indexing
myList=[1,2,3,4,5]
arr=np.array(myList)


In [19]:
print(arr[0])

1


In [20]:
#second element from array
print(arr[1])

2


In [21]:
print("the third element is:",arr[2],"and the fourth element is:",arr[3])

the third element is: 3 and the fourth element is: 4


In [22]:
#Access 2D array
my_List1=[1,2,3,4,5]
my_List2=[3,5,7,8,5]
my_List3=[5,7,2,5,9]

arr=np.array([my_List1,my_List2,my_List3])

In [23]:
arr

array([[1, 2, 3, 4, 5],
       [3, 5, 7, 8, 5],
       [5, 7, 2, 5, 9]])

In [24]:
arr[1,2]

7

In [25]:
arr[0,2]

3

In [26]:
print("second element on 1st row:",arr[0,1])

second element on 1st row: 2


In [27]:
print("fifth element on 1st row:",arr[1,4])

fifth element on 1st row: 5


In [28]:
my_List1=[1,2,3,4,5]
my_List2=[3,5,7,8,5]
my_List3=[5,7,2,5,9]
my_List4=[2,5,7,8,3]
my_List5=[3,6,2,1,7]
arr=np.array([my_List1,my_List2,my_List3,my_List4,my_List5])
print(arr)

[[1 2 3 4 5]
 [3 5 7 8 5]
 [5 7 2 5 9]
 [2 5 7 8 3]
 [3 6 2 1 7]]


In [29]:
print(arr.size)
print(arr.shape)
print("2nd element and 3rd row:",arr[2,1])
print("3rd element and 5th row:",arr[4,2])

25
(5, 5)
2nd element and 3rd row: 7
3rd element and 5th row: 2


In [30]:
#negative Indexing
my_List=[1,2,3,4,5]
arr=np.array(my_List)
print(arr[-1])

5


In [32]:
valArr=np.array([[1,2,3],[4,5,6]])
print(valArr[1,-3])

4


In [35]:
#NumPy Array Slicing -2D
valArr=np.array([[1,2,3],[4,5,6]])
print(valArr[0:2])

[[1 2 3]
 [4 5 6]]


In [56]:
#NumPy Array Slicing -1D
my_List=[1,2,3,4,5]  
arr=np.array(my_List)
print(arr[1:])

[2 3 4 5]


In [43]:
my_List=[1,2,3,4,5]
arr=np.array(my_List)
arr[-1:-3:-1]

array([5, 4])

In [50]:
my_List=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(my_List)
print(arr[1::2])

[ 2  4  6  8 10]


In [59]:
my_List1=[1,2,3,4,5]
my_List2=[3,5,7,8,5]
my_List3=[5,7,2,5,9]

arr=np.array([my_List1,my_List2,my_List3])
print(arr)

[[1 2 3 4 5]
 [3 5 7 8 5]
 [5 7 2 5 9]]


In [54]:
arr[1:,:]

array([[3, 5, 7, 8, 5],
       [5, 7, 2, 5, 9]])

In [62]:
#arr[1:,1:4]

array([[5, 7, 8],
       [7, 2, 5]])

In [79]:
my_List1=[1,2,3,4,5]
my_List2=[3,5,7,8,5]
my_List3=[5,7,2,5,9]

arr=np.array([my_List1,my_List2,my_List3])
print(arr[:1,1:4])

[[2 3 4]]


In [83]:
#Arange function

np.arange(10+1)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
# linspace
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [90]:
#let numpy choose the datatype
arr=np.array([True,False])
print(arr.dtype)

bool


In [91]:
#U-Unicode string
arr=np.array(["rohan","cholamattam","riya"])
print(arr.dtype)

<U11


In [94]:
arr=np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [104]:
# arr=np.array([1,2,3,4,5],dtype=np.int64)
# print(arr.dtype)

In [105]:
#arr=np.array([1,2,3,4,5],dtype=float)
#print(arr)
#print(arr.dtype)

In [103]:
arr=np.array([1,2,3,4,5],dtype=np.float32)
print(arr.dtype)

float32


In [110]:
#Array Math
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
x+y



array([[ 6,  8],
       [10, 12]])

In [111]:
x-y

array([[-4, -4],
       [-4, -4]])

In [112]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [147]:
x=np.array([[1,2],[5,6]])
y=np.array([[5,6],[3,1]])
z=np.array([[2,3],[5,2]])
a=np.add(x,y)
np.add(y,a)

array([[11, 14],
       [11,  8]])

In [114]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [115]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [116]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [119]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [120]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [122]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [123]:
#Floor,Ceil,Round
x=np.array([1.8,2.2,3.9,4.5])

In [124]:
np.floor(x)

array([1., 2., 3., 4.])

In [125]:
np.ceil(x)

array([2., 3., 4., 5.])

In [127]:
np.round(x)

array([2., 2., 4., 4.])

In [130]:
x=np.array([1,2])
y=np.array([5,6])
x.dot(y)

17

In [131]:
np.dot(x,y)

17

In [136]:
x=np.array([[1,2],[5,6]])
y=np.array([[5,6],[3,1]])
z=np.array([[2,3],[5,2]])
print(x)
print(y)
print(x.dot(y))

[[1 2]
 [5 6]]
[[5 6]
 [3 1]]
[[11  8]
 [43 36]]


In [141]:
#axis=0/1 1:row 0:column
x=np.array([[1,2,3],[5,6,1],[2,9,7]])
print(x)
np.sum(x,axis=0)


[[1 2 3]
 [5 6 1]
 [2 9 7]]


array([ 8, 17, 11])

In [142]:
x=np.array([[1,2,3],[5,6,1],[2,9,7]])
print(x)
np.sum(x,axis=1)


[[1 2 3]
 [5 6 1]
 [2 9 7]]


array([ 6, 12, 18])

In [144]:
#Transpose
x.T

array([[1, 5, 2],
       [2, 6, 9],
       [3, 1, 7]])

In [148]:
#Numpy Array copy and view
arr=np.array([1,2,3,4,5])
x=arr #whatever changes happen in arr will save in x.this is called view

In [150]:
print(arr)

[1 2 3 4 5]


In [151]:
print(x)

[1 2 3 4 5]


In [153]:
arr[0]=100
print(arr)

[100   2   3   4   5]


In [155]:
print(x)

[100   2   3   4   5]


In [160]:
#Array copy
arr=np.array([1,2,3,4,5])
x = arr.copy()
print(arr)
print(x)
arr[1]=990
print(arr)
x[0]=100
print(x)

[1 2 3 4 5]
[1 2 3 4 5]
[  1 990   3   4   5]
[100   2   3   4   5]


In [176]:
#Numpy array reshaping
arr=np.arange(1,13)
arr.shape

(12,)

In [177]:
arr_new=arr.reshape(4,3)
print(arr_new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [178]:
#Flattening the arrays
#2D-----> 1D
arr_new.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [179]:
 #iterating arrays
arr_new=arr.reshape(4,3)  
for i in arr_new:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [180]:
#joining numpy arrays #1D
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [181]:
arr1=np.array([[1,2],[4,3]])
arr2=np.array([[4,5],[9,6]])
np.concatenate((arr1,arr2))#Default axis=0

array([[1, 2],
       [4, 3],
       [4, 5],
       [9, 6]])

In [182]:
arr1=np.array([[1,2],[4,3]])
arr2=np.array([[4,5],[9,6]])
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 4, 5],
       [4, 3, 9, 6]])

In [184]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [185]:
#pandas
import numpy as np
import pandas as pd


In [189]:
df=pd.Series([1.0,2.4,5.6,7.4,5.3,2.0,7.0])

In [190]:
df

0    1.0
1    2.4
2    5.6
3    7.4
4    5.3
5    2.0
6    7.0
dtype: float64

In [191]:
type(df)

pandas.core.series.Series

In [192]:
df.shape

(7,)

In [193]:
df.head()# display first n observation default=5


0    1.0
1    2.4
2    5.6
3    7.4
4    5.3
dtype: float64

In [195]:
df.tail()# display last n observation default=5

2    5.6
3    7.4
4    5.3
5    2.0
6    7.0
dtype: float64

In [196]:
#Panda Dataframe-using numpy dataset
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [202]:
data=np.arange(0,20).reshape(5,4)
df=pd.DataFrame(data,index=["row1","row2","row3","row4","row5"],columns=["column1","column2","column3","column4"])

In [205]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [206]:
type(df)

pandas.core.frame.DataFrame

In [207]:
df.head(2)

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7

In [209]:
df.tail(3)

column1  column2  column3  column4
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [213]:
#Accessing a row
df.loc['row1']

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int32

In [219]:
type(df.loc['row1'])


pandas.core.series.Series

In [221]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [220]:
#df.iloc[strt:end,start:end]
df.iloc[2:,2:]

column3  column4
row3       10       11
row4       14       15
row5       18       19

In [226]:
df.loc[['row1','row2']]

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7

In [228]:
df['column1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int32

In [231]:
df[['column1','column2']]

column1  column2
row1        0        1
row2        4        5
row3        8        9
row4       12       13
row5       16       17

In [235]:
#pandas dataframe - using Dict
data={"weight":[30,40,50,60],
       "height":[133,146,158,170]}
df=pd.DataFrame(data)
df

weight  height
0      30     133
1      40     146
2      50     158
3      60     170

In [ ]:
#Pandas Dataframe - using CSV
pd.read